import type { Canteen, MenuItem, Order } from './types'

export const CANTEENS: Canteen[] = [
  {
    id: '1',
    name: 'Kantin Bu Sari',
    owner: 'Bu Sari',
    image: 'https://images.unsplash.com/photo-1680674814945-7945d913319c?w=600&h=400&fit=crop&auto=format',
    status: 'buka',
    menuCount: 12,
    estimasi: '5–10 menit',
    description: 'Masakan rumahan, nasi dan lauk pilihan lengkap',
  },
  {
    id: '2',
    name: 'Kantin Putra',
    owner: 'Pak Putra',
    image: 'https://images.unsplash.com/photo-1761125066136-f657176f7525?w=600&h=400&fit=crop&auto=format',
    status: 'buka',
    menuCount: 8,
    estimasi: '5–8 menit',
    description: 'Mie dan bakso spesial, cita rasa autentik',
  },
  {
    id: '3',
    name: 'Kantin Sehat',
    owner: 'Bu Dewi',
    image: 'https://images.unsplash.com/photo-1680675027408-7232d86cbc47?w=600&h=400&fit=crop&auto=format',
    status: 'tutup',
    menuCount: 10,
    estimasi: '5–10 menit',
    description: 'Menu sehat dan bergizi untuk tubuh aktif',
  },
  {
    id: '4',
    name: 'Kantin Cepat',
    owner: 'Pak Budi',
    image: 'https://images.unsplash.com/photo-1680674774705-90b4904b3a7f?w=600&h=400&fit=crop&auto=format',
    status: 'buka',
    menuCount: 6,
    estimasi: '3–5 menit',
    description: 'Snack dan minuman siap saji untuk istirahat singkat',
  },
  {
    id: '5',
    name: 'Kantin Nusantara',
    owner: 'Bu Ratna',
    image: 'https://images.unsplash.com/photo-1680675027408-7232d86cbc47?w=600&h=400&fit=crop&auto=format',
    status: 'buka',
    menuCount: 9,
    estimasi: '8–12 menit',
    description: 'Masakan khas Nusantara, beragam pilihan lauk tradisional',
  },
]

export const MENUS: Record<string, MenuItem[]> = {
  '1': [
    {
      id: 'm1',
      name: 'Nasi Ayam',
      description: 'Ayam crispy + nasi + sambal pedas',
      price: 10000,
      image: 'https://images.unsplash.com/photo-1680674814945-7945d913319c?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 20,
    },
    {
      id: 'm2',
      name: 'Nasi Goreng',
      description: 'Nasi goreng spesial + telur + ayam suwir',
      price: 11000,
      image: 'https://images.unsplash.com/photo-1680674774705-90b4904b3a7f?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 15,
    },
    {
      id: 'm3',
      name: 'Mie Goreng',
      description: 'Mie goreng + telur mata sapi + sayuran',
      price: 8000,
      image: 'https://images.unsplash.com/photo-1761125066136-f657176f7525?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 18,
    },
    {
      id: 'm4',
      name: 'Roti Bakar',
      description: 'Roti bakar pilihan: cokelat / keju / strawberry',
      price: 6000,
      image: 'https://images.unsplash.com/photo-1612827788868-c8632040ab64?w=400&h=300&fit=crop&auto=format',
      category: 'snack',
      available: true,
      stock: 25,
    },
    {
      id: 'm5',
      name: 'Bakso Kuah',
      description: 'Bakso sapi + kuah kaldu gurih + bihun',
      price: 9000,
      image: 'https://images.unsplash.com/photo-1680675027408-7232d86cbc47?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: false,
      stock: 0,
    },
    {
      id: 'm6',
      name: 'Es Teh Manis',
      description: 'Teh manis dingin segar, es banyak',
      price: 4000,
      image: 'https://images.unsplash.com/photo-1601390395693-364c0e22031a?w=400&h=300&fit=crop&auto=format',
      category: 'minuman',
      available: true,
      stock: 50,
    },
    {
      id: 'm7',
      name: 'Es Jeruk',
      description: 'Jeruk peras segar + es + sedikit sirup',
      price: 5000,
      image: 'https://images.unsplash.com/photo-1533007716222-4b465613a984?w=400&h=300&fit=crop&auto=format',
      category: 'minuman',
      available: true,
      stock: 30,
    },
    {
      id: 'm8',
      name: 'Kerupuk Udang',
      description: 'Kerupuk udang renyah siap makan',
      price: 2000,
      image: 'https://images.unsplash.com/photo-1554997433-bd88e371760b?w=400&h=300&fit=crop&auto=format',
      category: 'snack',
      available: true,
      stock: 100,
    },
  ],
  '2': [
    {
      id: 'm9',
      name: 'Mie Ayam',
      description: 'Mie ayam bakso + pangsit goreng',
      price: 10000,
      image: 'https://images.unsplash.com/photo-1761125066136-f657176f7525?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 12,
    },
    {
      id: 'm10',
      name: 'Bakso Campur',
      description: 'Bakso campur + mie + pangsit + kuah',
      price: 11000,
      image: 'https://images.unsplash.com/photo-1680675027408-7232d86cbc47?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 10,
    },
    {
      id: 'm11',
      name: 'Soto Ayam',
      description: 'Soto ayam + nasi + telur + kerupuk',
      price: 10000,
      image: 'https://images.unsplash.com/photo-1680674814945-7945d913319c?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: true,
      stock: 8,
    },
    {
      id: 'm12',
      name: 'Es Teh',
      description: 'Es teh manis segar',
      price: 4000,
      image: 'https://images.unsplash.com/photo-1601390395693-364c0e22031a?w=400&h=300&fit=crop&auto=format',
      category: 'minuman',
      available: true,
      stock: 40,
    },
  ],
  '3': [
    {
      id: 'm13',
      name: 'Salad Buah',
      description: 'Aneka buah segar + yogurt madu',
      price: 12000,
      image: 'https://images.unsplash.com/photo-1680675027408-7232d86cbc47?w=400&h=300&fit=crop&auto=format',
      category: 'makanan',
      available: false,
      stock: 0,
    },
  ],
  '4': [
    {
      id: 'm14',
      name: 'Gorengan Mix',
      description: 'Tahu, tempe, bakwan goreng campur',
      price: 5000,
      image: 'https://images.unsplash.com/photo-1612827788868-c8632040ab64?w=400&h=300&fit=crop&auto=format',
      category: 'snack',
      available: true,
      stock: 50,
    },
    {
      id: 'm15',
      name: 'Minuman Botol',
      description: 'Teh botol, air mineral, soda',
      price: 5000,
      image: 'https://images.unsplash.com/photo-1533007716222-4b465613a984?w=400&h=300&fit=crop&auto=format',
      category: 'minuman',
      available: true,
      stock: 60,
    },
  ],
}

// Initially empty — orders are created when students place them
export const ORDER_HISTORY: Order[] = []

export const VENDOR_ORDERS: Order[] = [
  {
    id: 'A001',
    items: [
      { name: 'Nasi Ayam', qty: 1, price: 10000 },
      { name: 'Es Teh Manis', qty: 1, price: 4000 },
    ],
    total: 14000,
    canteen: 'Kantin Bu Sari',
    canteenId: '1',
    pickup: 'istirahat1',
    pickupLabel: 'Istirahat 1 — 10:00',
    status: 'diproses',
    date: '01 September 2026',
    student: 'Adib',
    kelas: 'XI',
    paymentMethod: 'qris',
    paymentStatus: 'berhasil',
    notes: 'Sambal terpisah ya',
  },
  {
    id: 'A002',
    items: [{ name: 'Mie Goreng', qty: 1, price: 8000 }],
    total: 8000,
    canteen: 'Kantin Bu Sari',
    canteenId: '1',
    pickup: 'istirahat1',
    pickupLabel: 'Istirahat 1 — 10:00',
    status: 'baru',
    date: '01 September 2026',
    student: 'Raka',
    kelas: 'XI',
    paymentMethod: 'kantin',
    paymentStatus: 'menunggu',
  },
  {
    id: 'A003',
    items: [
      { name: 'Nasi Goreng', qty: 2, price: 11000 },
      { name: 'Es Jeruk', qty: 2, price: 5000 },
    ],
    total: 32000,
    canteen: 'Kantin Bu Sari',
    canteenId: '1',
    pickup: 'istirahat1',
    pickupLabel: 'Istirahat 1 — 10:00',
    status: 'siap',
    date: '01 September 2026',
    student: 'Siti',
    kelas: 'X',
    paymentMethod: 'qris',
    paymentStatus: 'berhasil',
  },
  {
    id: 'A004',
    items: [{ name: 'Roti Bakar', qty: 3, price: 6000 }],
    total: 18000,
    canteen: 'Kantin Bu Sari',
    canteenId: '1',
    pickup: 'istirahat2',
    pickupLabel: 'Istirahat 2 — 12:00',
    status: 'baru',
    date: '01 September 2026',
    student: 'Bintang',
    kelas: 'XII',
    paymentMethod: 'kantin',
    paymentStatus: 'menunggu',
    notes: 'Keju double',
  },
  {
    id: 'A005',
    items: [
      { name: 'Nasi Ayam', qty: 1, price: 10000 },
      { name: 'Kerupuk Udang', qty: 2, price: 2000 },
    ],
    total: 14000,
    canteen: 'Kantin Bu Sari',
    canteenId: '1',
    pickup: 'istirahat2',
    pickupLabel: 'Istirahat 2 — 12:00',
    status: 'selesai',
    date: '01 September 2026',
    student: 'Anisa',
    kelas: 'X',
    paymentMethod: 'qris',
    paymentStatus: 'berhasil',
  },
]

export const DAILY_CHART_DATA = [
  { hour: '07:00', orders: 3 },
  { hour: '08:00', orders: 8 },
  { hour: '09:00', orders: 22 },
  { hour: '10:00', orders: 47 },
  { hour: '11:00', orders: 12 },
  { hour: '12:00', orders: 38 },
  { hour: '13:00', orders: 15 },
  { hour: '14:00', orders: 4 },
]

export const formatRupiah = (amount: number): string => {
  return `Rp${amount.toLocaleString('id-ID')}`
}
